export const Catalog = () => import('./Catalog.vue')
export const About = () => import('./About.vue')
export const Journal = () => import('./Journal.vue')
export const Product = () => import('./Product.vue')
export const Cart = () => import('./Cart.vue')
export const Login = () => import('./Login.vue')
export const Register = () => import('./Register.vue')
